-- Your SQL goes here
CREATE TABLE preset_items (
    id SERIAL PRIMARY KEY NOT NULL,
    preset_id INTEGER NOT NULL REFERENCES presets(id) ON DELETE CASCADE,
    point_id INTEGER NOT NULL REFERENCES points(id) ON DELETE CASCADE,
    val INTEGER NOT NULL DEFAULT 0 CHECK (val > -1)
);
